### PR TITLE
typo_fix dev-requirements.txt

### PR DESCRIPTION
**Pull request by Zatyrus**
Fixed three small typos in the dev-requirements.txt that lead to a raised error during `pip install -r dev-requirements.txt`.

### CODE REVIEW

**Comment by Zatyrus** [comment]
Using the opportunity for such a small addition to test the commit routine.

I would prefer to directly push minor changes such as this directly into the devel branch, but can also keep up  the routine of one branch per change.

@aarpon 
You might want to merge this change into master rather soon as it interferes with the process of installation.

**Review by aarpon — CHANGES_REQUESTED** [review]
Could you please set:

```
nuitka==2.4.11
zstandard==0.23.0
```

**Comment by aarpon** [comment]
You can definitely push small changes like this directly to devel. Please let me know if you are prevented from doing this by some settings. Branches are only needed for changes that would disrupt devel for longer time.

**Comment by Zatyrus** [comment]
> Could you please set:
> 
> ```
> nuitka==2.4.11
> zstandard==0.23.0
> ```

Done!

**Review by aarpon — APPROVED** [review]

**Pull request merged**
